POST http://localhost:3000/posts 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIwLCJlbWFpbCI6ImFndXN0aW5hLm1hcnRpbmV6QGV4YW1wbGUuY29tIiwiaWF0IjoxNzYyMjkwMzM1LCJleHAiOjE3NjIyOTM5MzUsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMCJ9.X7MYLV47_ni88lbfabHPJpTHQ8Ww8Li1gXwqxpwSZl0
{
  "title": "Mi primer post Valentina",
  "postType": "post",
  "slug": "mi-primer-post225",
  "status": "draft",
  "content": "Este es el contenido del post.",
  "schema": "{\"type\":\"object\",\"properties\":{\"example\":{\"type\":\"string\"}}}",
  "featuredImageUrl": "https://example.com/image.jpg",
  "publishOn": "2025-09-01T12:00:00.000Z",
  "tags": ["nestjs", "typescript", "blog"],
"metaOptions": {
    "metaValue": "{\"sidebarEnabled\": true, \"footerActive\": true}"
  },
  "authorId": 15,
  "tags": [1]
}
