POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "Mariana",
  "lastName": "López",
  "email": "mariana.lopez@example.com",
  "password": "Mariana#2026"
}


POST http://localhost:3000/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIwLCJlbWFpbCI6ImFndXN0aW5hLm1hcnRpbmV6QGV4YW1wbGUuY29tIiwiaWF0IjoxNzYyMjg4Nzk2LCJleHAiOjE3NjIyOTIzOTYsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMCJ9.RMYRK8Ens1TaBPEM0PHaDBbO1eHPpQeVBG8MSe5K_ZE
{
  "users": [
    {
      "firstName": "Valentina",
      "lastName": "Martinez",
      "email": "valentina@martinez.com",
      "password": "V!m123456"
    },
    {
      "firstName": "Santiago",
      "lastName": "Fernandez",
      "email": "santiago@fernandez.com",
      "password": "S!f654321"
    },
    {
      "firstName": "Camila",
      "lastName": "Gonzalez",
      "email": "camila@gonzalez.com",
      "password": "C!g987654"
    },
    {
      "firstName": "Diego",
      "lastName": "Rodriguez",
      "email": "diego@rodriguez.com",
      "password": "D!r321987"
    }
  ]
}