GET http://localhost:3000/users/?limit=10&page=20
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIwLCJlbWFpbCI6ImFndXN0aW5hLm1hcnRpbmV6QGV4YW1wbGUuY29tIiwiaWF0IjoxNzY4NTAzMjEyLCJleHAiOjE3Njg1MDY4MTIsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMCJ9.-m5nrCsboBqlCfS0OJbrpPGlJmKbgg1XRPscdFtqi48

GET http://localhost:3000/users/1?limit=10&page=20
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIwLCJlbWFpbCI6ImFndXN0aW5hLm1hcnRpbmV6QGV4YW1wbGUuY29tIiwiaWF0IjoxNzY4NTAzMjEyLCJleHAiOjE3Njg1MDY4MTIsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMCJ9.-m5nrCsboBqlCfS0OJbrpPGlJmKbgg1XRPscdFtqi48
